import type { ReactNode } from 'react';
import type {
  PopoverResolver,
  ClickOutsideConfig,
  PopoverCache,
  CollisionConfig,
  FocusLockOptions,
  PopoverSlotComponents,
  ZIndexBaseMap,
} from '../types';

/**
 * Props for the {@link PopoverProvider} component.
 *
 * @template TData - The type of resolved data payloads.
 * @template TContext - The type of global shared context.
 */
export interface PopoverProviderProps<TData = unknown, TContext = unknown> {
  /** React child elements rendered inside the provider. */
  children: ReactNode;

  /**
   * Optional schema instance generated by `createPopoverSchema`.
   * Automatically supplies `resolveData` and default display options if provided.
   */
  schema?: unknown;

  /**
   * The resolver callback responsible for loading data for each popover.
   * Can resolve data synchronously or asynchronously. Optional if schema is provided.
   */
  resolveData?: PopoverResolver<TData, TContext>;

  /** Optional initial context values passed to the data resolver. */
  initialContext?: TContext;

  /** Click outside configuration settings (enabled by default). */
  clickOutside?: ClickOutsideConfig;

  /** If true (default), enables closing topmost active popovers on Escape keydown. */
  enableKeyboardClose?: boolean;

  /**
   * If true, closing a parent popover will also recursively close all of its pinned descendants.
   * Defaults to false (pinned descendants remain open).
   */
  closePinnedDescendants?: boolean;

  /** Optional custom synchronous or asynchronous cache provider. */
  cache?: PopoverCache<TData>;

  /** Global default settings for boundary collision checking. */
  collision?: CollisionConfig;

  /** If true, enables keyboard arrow key navigation (default: true). */
  enableArrowNavigation?: boolean;

  /** True to allow dragging when popover card is pinned/floating (default: true). */
  allowDragWhenPinned?: boolean;

  /** True to allow dragging when popover card is unpinned/trailing (default: true). */
  allowDragWhenUnpinned?: boolean;

  /** If true, prints Zustand state updates to the console (default: false). */
  debug?: boolean;

  /** Horizontal offset step applied per level of the cascade trail (default: 8px). */
  cascadeOffsetStep?: number;

  /** Duration of the exit transition in milliseconds before the card is unmounted (default: 0). */
  exitTransitionDuration?: number;

  /** Default distance gap offset override from trigger in pixels (default: 8px). */
  defaultOffset?: number;

  /** Base z-index offset applied to all popover layers (default: 1000). */
  baseZIndex?: number;

  /** Global default CSS animation class applied during mounting (default: 'mounting'). */
  mountingClassName?: string;

  /** Global default CSS animation class applied during unmounting (default: 'unmounting'). */
  unmountingClassName?: string;

  /** Global default CSS animation class applied during mounted (default: 'mounted'). */
  mountedClassName?: string;

  /** Responsive layout transformation mode ('auto' | 'popover' | 'bottom-sheet' | 'modal'). */
  responsiveMode?: 'auto' | 'popover' | 'bottom-sheet' | 'modal';

  /** Mobile viewport width breakpoint in pixels (default: 640). */
  mobileBreakpoint?: number;

  /** Active stack group zone ID filter (e.g. 'sidebar', 'canvas', or null for all). */
  stackGroup?: string | null;

  /** Global default focus lock options. */
  focusLockOptions?: FocusLockOptions;

  /** Global component slots overrides. */
  components?: PopoverSlotComponents;

  /** Base z-index depth offsets per stack group ID. */
  zIndexBaseMap?: ZIndexBaseMap;
}
