/**
 * React Context, Provider, and Custom Hooks Engine for popover-trail.
 *
 * @module context
 */

import * as React from 'react';
import {
  createContext,
  useContext,
  useState,
  useMemo,
  useCallback,
  useEffect,
  type ReactNode,
} from 'react';
import { useStore } from 'zustand';
import type { StoreApi } from 'zustand/vanilla';
import { createPopoverStore } from './store';
import { useEventListener } from './hooks/useEventListener';
import { useClickOutside } from './hooks/useClickOutside';
import { invariant } from './utils/invariant';
import { isDeepEqual } from './utils/storeHelpers';
import {
  validateProviderResolver,
  validateCascadeStep,
  validateDefaultOffset,
  validateBaseZIndex,
  validateExitDuration,
} from './utils/devWarnings';
import {
  type PopoverStore,
  type PopoverResolver,
  type ClickOutsideConfig,
  type PopoverCache,
  type CollisionConfig,
  type FocusLockOptions,
  type PopoverSlotComponents,
  type ZIndexBaseMap,
} from './types';

/**
 * Context container holding the Zustand StoreApi instance.
 *
 * @internal
 */
const PopoverStoreContext = createContext<StoreApi<PopoverStore<unknown, unknown>> | null>(null);
PopoverStoreContext.displayName = 'PopoverStoreContext';

/**
 * Context container holding the current Popover card's unique key ID.
 * Used by `<PopoverTrigger>` components to detect if they are nested and resolve
 * their parent popover key automatically.
 */
export const PopoverCardContext = createContext<string | null>(null);
PopoverCardContext.displayName = 'PopoverCardContext';

/**
 * Props for the {@link PopoverProvider} component.
 *
 * @template TData - The type of resolved data payloads.
 * @template TContext - The type of global shared context.
 */
export interface PopoverProviderProps<TData = unknown, TContext = unknown> {
  /** React child elements rendered inside the provider. */
  children: ReactNode;

  /**
   * Optional schema instance generated by `createPopoverSchema`.
   * Automatically supplies `resolveData` and default display options if provided.
   */
  schema?: unknown;

  /**
   * The resolver callback responsible for loading data for each popover.
   * Can resolve data synchronously or asynchronously. Optional if schema is provided.
   */
  resolveData?: PopoverResolver<TData, TContext>;

  /** Optional initial context values passed to the data resolver. */
  initialContext?: TContext;

  /** Click outside configuration settings (enabled by default). */
  clickOutside?: ClickOutsideConfig;

  /** If true (default), enables closing topmost active popovers on Escape keydown. */
  enableKeyboardClose?: boolean;

  /**
   * If true, closing a parent popover will also recursively close all of its pinned descendants.
   * Defaults to false (pinned descendants remain open).
   */
  closePinnedDescendants?: boolean;

  /** Optional custom synchronous or asynchronous cache provider. */
  cache?: PopoverCache<TData>;

  /** Global default settings for boundary collision checking. */
  collision?: CollisionConfig;

  /** If true, enables keyboard arrow key navigation (default: true). */
  enableArrowNavigation?: boolean;

  /** True to allow dragging when popover card is pinned/floating (default: true). */
  allowDragWhenPinned?: boolean;

  /** True to allow dragging when popover card is unpinned/trailing (default: true). */
  allowDragWhenUnpinned?: boolean;

  /** If true, prints Zustand state updates to the console (default: false). */
  debug?: boolean;

  /** Horizontal offset step applied per level of the cascade trail (default: 8px). */
  cascadeOffsetStep?: number;

  /** Duration of the exit transition in milliseconds before the card is unmounted (default: 0). */
  exitTransitionDuration?: number;

  /** Default distance gap offset override from trigger in pixels (default: 8px). */
  defaultOffset?: number;

  /** Base z-index offset applied to all popover layers (default: 1000). */
  baseZIndex?: number;

  /** Global default CSS animation class applied during mounting (default: 'mounting'). */
  mountingClassName?: string;

  /** Global default CSS animation class applied during unmounting (default: 'unmounting'). */
  unmountingClassName?: string;

  /** Global default CSS animation class applied during mounted (default: 'mounted'). */
  mountedClassName?: string;

  /** Responsive layout transformation mode ('auto' | 'popover' | 'bottom-sheet' | 'modal'). */
  responsiveMode?: 'auto' | 'popover' | 'bottom-sheet' | 'modal';

  /** Mobile viewport width breakpoint in pixels (default: 640). */
  mobileBreakpoint?: number;

  /** Active stack group zone ID filter (e.g. 'sidebar', 'canvas', or null for all). */
  stackGroup?: string | null;

  /** Global default focus lock options. */
  focusLockOptions?: FocusLockOptions;

  /** Global component slots overrides. */
  components?: PopoverSlotComponents;

  /** Base z-index depth offsets per stack group ID. */
  zIndexBaseMap?: ZIndexBaseMap;
}

/**
 * Internal hook encapsulating keyboard event handling for the provider (SRP).
 */
function usePopoverKeyboardShortcuts<TData, TContext>(
  store: StoreApi<PopoverStore<TData, TContext>>,
  enableKeyboardClose: boolean,
) {
  const handleKeyDown = useCallback(
    (e: KeyboardEvent) => {
      if (!enableKeyboardClose || e.defaultPrevented) return;
      if (e.key === 'Escape') {
        const state = store.getState();
        const hasActive = state.trail.length > 0 || state.floating.length > 0;
        if (hasActive) {
          e.preventDefault();
          e.stopPropagation();
          state.closeTopmost();
        }
      }
    },
    [enableKeyboardClose, store],
  );

  useEventListener('keydown', handleKeyDown);
}

/**
 * Internal hook managing efficient prop synchronization into store state (SRP & Performance).
 */
function usePopoverPropSync<TData, TContext>(
  store: StoreApi<PopoverStore<TData, TContext>>,
  props: PopoverProviderProps<TData, TContext>,
  activeResolver: PopoverResolver<TData, TContext>,
) {
  useEffect(() => {
    store.getState().batchUpdates(() => {
      const state = store.getState();
      const enableArrowNav = Boolean(props.enableArrowNavigation ?? true);
      if (state.enableArrowNavigation !== enableArrowNav) {
        state.setEnableArrowNavigation(enableArrowNav);
      }

      const dragPinned = Boolean(props.allowDragWhenPinned ?? true);
      if (state.allowDragWhenPinned !== dragPinned) {
        state.setAllowDragWhenPinned(dragPinned);
      }

      const dragUnpinned = Boolean(props.allowDragWhenUnpinned ?? true);
      if (state.allowDragWhenUnpinned !== dragUnpinned) {
        state.setAllowDragWhenUnpinned(dragUnpinned);
      }

      const dbg = Boolean(props.debug ?? false);
      if (state.debug !== dbg) {
        state.setDebug(dbg);
      }

      const cascadeStep = Number(props.cascadeOffsetStep ?? 8);
      if (state.cascadeOffsetStep !== cascadeStep) {
        state.setCascadeOffsetStep(cascadeStep);
      }

      const exitDur = Number(props.exitTransitionDuration ?? 0);
      if (state.exitTransitionDuration !== exitDur) {
        state.setExitTransitionDuration(exitDur);
      }

      const defOffset = Number(props.defaultOffset ?? 8);
      if (state.defaultOffset !== defOffset) {
        state.setDefaultOffset(defOffset);
      }

      const zIndex = Number(props.baseZIndex ?? 1000);
      if (state.baseZIndex !== zIndex) {
        state.setBaseZIndex(zIndex);
      }

      const mountingName = String(props.mountingClassName ?? 'mounting');
      const unmountingName = String(props.unmountingClassName ?? 'unmounting');
      const mountedName = String(props.mountedClassName ?? 'mounted');
      if (
        state.mountingClassName !== mountingName ||
        state.unmountingClassName !== unmountingName ||
        state.mountedClassName !== mountedName
      ) {
        state.setGlobalAnimationClassNames(mountingName, unmountingName, mountedName);
      }

      if (state.context !== props.initialContext) {
        state.setContext(props.initialContext as TContext);
      }

      if (state.resolveData !== activeResolver) {
        state.setResolveData(activeResolver);
      }

      const closePinned = Boolean(props.closePinnedDescendants ?? false);
      if (state.closePinnedDescendants !== closePinned) {
        state.setClosePinnedDescendants(closePinned);
      }

      const respMode = props.responsiveMode ?? 'auto';
      if (state.responsiveMode !== respMode) {
        state.setResponsiveMode(respMode);
      }

      const mobBreakpoint = Number(props.mobileBreakpoint ?? 640);
      if (state.mobileBreakpoint !== mobBreakpoint) {
        state.setMobileBreakpoint(mobBreakpoint);
      }

      const stackGroupFilter = props.stackGroup ?? null;
      if (state.activeStackGroup !== stackGroupFilter) {
        state.setStackGroupFilter(stackGroupFilter);
      }

      if (props.focusLockOptions && !isDeepEqual(state.focusLockOptions, props.focusLockOptions)) {
        state.setFocusLockOptions(props.focusLockOptions);
      }

      const collisionConfig = props.collision ?? null;
      if (!isDeepEqual(state.collisionConfig, collisionConfig)) {
        state.setCollisionConfig(collisionConfig);
      }

      const slotComponents = props.components ?? null;
      if (state.components !== slotComponents) {
        state.setSlotComponents(slotComponents);
      }

      const zIndexMap = props.zIndexBaseMap ?? null;
      if (!isDeepEqual(state.zIndexBaseMap, zIndexMap)) {
        state.setZIndexBaseMap(zIndexMap);
      }
    });
  }, [
    store,
    props.enableArrowNavigation,
    props.allowDragWhenPinned,
    props.allowDragWhenUnpinned,
    props.debug,
    props.cascadeOffsetStep,
    props.exitTransitionDuration,
    props.defaultOffset,
    props.baseZIndex,
    props.mountingClassName,
    props.unmountingClassName,
    props.mountedClassName,
    props.initialContext,
    activeResolver,
    props.closePinnedDescendants,
    props.collision,
    props.responsiveMode,
    props.mobileBreakpoint,
    props.stackGroup,
    props.focusLockOptions,
    props.components,
    props.zIndexBaseMap,
  ]);
}

/**
 * PopoverProvider component that instantiates the Zustand store and injects it
 * into the React context tree.
 */
export function PopoverProvider<TData = unknown, TContext = unknown>(
  props: PopoverProviderProps<TData, TContext>,
) {
  const {
    children,
    schema,
    resolveData,
    initialContext,
    clickOutside,
    enableKeyboardClose = true,
    cascadeOffsetStep = 8,
    exitTransitionDuration = 0,
    defaultOffset = 8,
    baseZIndex = 1000,
    cache,
  } = props;

  validateProviderResolver(Boolean(resolveData || schema));
  validateCascadeStep(cascadeOffsetStep);
  validateDefaultOffset(defaultOffset);
  validateBaseZIndex(baseZIndex);
  validateExitDuration(exitTransitionDuration);

  const activeResolver = useMemo<PopoverResolver<TData, TContext>>(() => {
    if (resolveData) return resolveData;
    const schemaInstance = schema as
      | { createResolver?: <TC = TContext>() => PopoverResolver<TData, TC> }
      | undefined;
    if (schemaInstance && typeof schemaInstance.createResolver === 'function') {
      return schemaInstance.createResolver();
    }
    return () =>
      Promise.reject(new Error('No resolveData callback or schema provided to PopoverProvider'));
  }, [resolveData, schema]);

  // Use useState to instantiate the store once
  const [store] = useState(() =>
    createPopoverStore<TData, TContext>(activeResolver, initialContext, cache),
  );

  // Synchronize all provider props efficiently
  usePopoverPropSync(store, props, activeResolver);

  // Cleanup on Provider unmount: abort all in-flight requests and reset state
  useEffect(() => {
    return () => {
      store.getState().destroy();
    };
  }, [store]);

  // Handle Escape key closing globally
  usePopoverKeyboardShortcuts(store, enableKeyboardClose);

  // Setup click outside logic using custom hook
  useClickOutside({
    store: store as StoreApi<PopoverStore<unknown, unknown>>,
    clickOutside,
  });

  return (
    <PopoverStoreContext value={store as StoreApi<PopoverStore<unknown, unknown>>}>
      {children}
    </PopoverStoreContext>
  );
}

/**
 * Custom selector hook for direct access to reactive slices of the Popover Zustand store.
 *
 * @template TSelected - The extracted state slice type.
 * @template TData - The type of resolved data payloads.
 * @template TContext - The type of global shared context.
 *
 * @param selector - Function to extract a slice of the store state.
 * @param equalityFn - Optional custom equality function to prevent redundant re-renders.
 * @returns The selected state slice.
 * @throws {Error} If called outside a `<PopoverProvider>`.
 *
 * @example
 * ```tsx
 * const activeCount = usePopoverStore((state) => state.trail.length);
 * ```
 *
 * @see {@link PopoverProvider}
 * @see {@link usePopoverStoreApi}
 */
export function usePopoverStore<TSelected, TData = unknown, TContext = unknown>(
  selector: (state: PopoverStore<TData, TContext>) => TSelected,
  equalityFn?: (a: TSelected, b: TSelected) => boolean,
): TSelected {
  const store = usePopoverStoreApi<TData, TContext>();

  const memoizedSelector = useMemo(() => {
    if (!equalityFn) return selector;
    let hasPrev = false;
    let prevSelected: TSelected | undefined;
    return (state: PopoverStore<TData, TContext>): TSelected => {
      const nextSelected = selector(state);
      if (hasPrev && equalityFn(prevSelected as TSelected, nextSelected)) {
        return prevSelected as TSelected;
      }
      hasPrev = true;
      prevSelected = nextSelected;
      return nextSelected;
    };
  }, [selector, equalityFn]);

  return useStore(store, memoizedSelector);
}

/**
 * Hook to retrieve the raw store API instance directly, without subscribing to state changes.
 * Useful for performance-sensitive imperative writes (e.g. inside drag events or event handlers).
 *
 * @template TData - The type of resolved data payloads.
 * @template TContext - The type of global shared context.
 *
 * @returns The raw Zustand StoreApi instance matching PopoverStore.
 * @throws {Error} If called outside a `<PopoverProvider>`.
 *
 * @example
 * ```tsx
 * const storeApi = usePopoverStoreApi();
 * const currentState = storeApi.getState();
 * ```
 *
 * @see {@link PopoverProvider}
 * @see {@link usePopoverStore}
 */
export function usePopoverStoreApi<TData = unknown, TContext = unknown>(): StoreApi<
  PopoverStore<TData, TContext>
> {
  const store = useContext(PopoverStoreContext);
  invariant(store, 'usePopoverStoreApi must be used within a PopoverProvider');
  return store as StoreApi<PopoverStore<TData, TContext>>;
}

import type { RegisteredKeys, RegisteredDataMap } from './types/registerTypes';

/**
 * Hook to retrieve public popover store action dispatch methods.
 *
 * @remarks
 * Excludes internal state lifecycle actions like `openRoot` and `destroy`.
 *
 * @template TData - The type of resolved data payloads.
 * @template TContext - The type of global shared context.
 * @returns Object containing dispatch actions.
 */
export function usePopoverActions<
  TData = RegisteredDataMap[RegisteredKeys],
  TContext = unknown,
  TPopoverKey extends string = RegisteredKeys,
>(): Readonly<PopoverStore<TData, TContext, TPopoverKey>['actions']> {
  const store = useContext(PopoverStoreContext);
  if (!store) {
    throw new Error('usePopoverActions must be used within a PopoverProvider');
  }
  return store.getState().actions as Readonly<
    PopoverStore<TData, TContext, TPopoverKey>['actions']
  >;
}

import {
  usePopoverTrail,
  usePopoverFloating,
  usePopoverOffsets,
  useIsPopoverPinned,
  usePopoverEntry,
  usePopoverEntryStatus,
  usePopoverZIndex,
  useIsPopoverTopMost,
  usePopoverOffset,
  usePopoverContext,
  usePopoverCollisionConfig,
  useIsPopoverOpen,
  usePopover,
  usePopoverData,
  usePopoverHydration,
  type PopoverHydrationState,
} from './hooks/usePopoverSelectors';

export {
  usePopoverTrail,
  usePopoverFloating,
  usePopoverOffsets,
  useIsPopoverPinned,
  usePopoverEntry,
  usePopoverEntryStatus,
  usePopoverZIndex,
  useIsPopoverTopMost,
  usePopoverOffset,
  usePopoverContext,
  usePopoverCollisionConfig,
  useIsPopoverOpen,
  usePopover,
  usePopoverData,
  usePopoverHydration,
  type PopoverHydrationState,
};

export {
  usePopoverTimeline,
  type PopoverTimelineItem,
  type UsePopoverTimelineResult,
} from './hooks/usePopoverTimeline';

export { usePopoverTrigger, usePopoverNestedTrigger } from './hooks/usePopoverTriggers';
export { PopoverPortal, type PopoverPortalProps } from './components/PopoverPortal';

/**
 * Factory creating pre-bound PopoverProvider and custom hooks for a specific shared global app TContext.
 * Eliminates repeating generic parameter types across components.
 *
 * @template TContext - Global shared context type.
 *
 * @example
 * ```tsx
 * const { Provider, useContext, useActions } = definePopoverContext<MyGlobalContext>();
 * ```
 *
 * @see {@link PopoverProvider}
 * @see {@link usePopoverContext}
 */
export function definePopoverContext<TContext = unknown>() {
  return {
    useContext: () => usePopoverContext<TContext>(),
    useActions: <TData = unknown,>() => usePopoverActions<TData, TContext>(),
    useStoreApi: <TData = unknown,>() => usePopoverStoreApi<TData, TContext>(),
    Provider: PopoverProvider as React.ComponentType<PopoverProviderProps<unknown, TContext>>,
  };
}
