/**
 * React Context, Provider, and Custom Hooks Engine for popover-trail.
 *
 * @module context
 */

import * as React from 'react';
import {
  createContext,
  useContext,
  useState,
  useMemo,
  useCallback,
  useEffect,
  useRef,
  type ReactNode,
} from 'react';
import { useStore } from 'zustand';
import type { StoreApi } from 'zustand/vanilla';
import { createPopoverStore } from './store';
import { useEventListener } from './hooks/useEventListener';
import { invariant } from './utils/invariant';
import { isDeepEqual, getEventPath, getEventTarget } from './utils/storeHelpers';
import {
  validateProviderResolver,
  validateCascadeStep,
  validateDefaultOffset,
  validateBaseZIndex,
  validateExitDuration,
} from './utils/devWarnings';
import {
  type PopoverStore,
  type PopoverResolver,
  type ClickOutsideConfig,
  type PopoverCache,
  type CollisionConfig,
  type FocusLockOptions,
  type PopoverSlotComponents,
  type ZIndexBaseMap,
} from './types';

/**
 * Context container holding the Zustand StoreApi instance.
 *
 * @internal
 */
const PopoverStoreContext = createContext<StoreApi<PopoverStore<unknown, unknown>> | null>(null);
PopoverStoreContext.displayName = 'PopoverStoreContext';

/**
 * Context container holding the current Popover card's unique key ID.
 * Used by `<PopoverTrigger>` components to detect if they are nested and resolve
 * their parent popover key automatically.
 */
export const PopoverCardContext = createContext<string | null>(null);
PopoverCardContext.displayName = 'PopoverCardContext';

/**
 * Props for the {@link PopoverProvider} component.
 *
 * @template TData - The type of resolved data payloads.
 * @template TContext - The type of global shared context.
 */
export interface PopoverProviderProps<TData = unknown, TContext = unknown> {
  /** React child elements rendered inside the provider. */
  children: ReactNode;

  /**
   * Optional schema instance generated by `createPopoverSchema`.
   * Automatically supplies `resolveData` and default display options if provided.
   */
  schema?: unknown;

  /**
   * The resolver callback responsible for loading data for each popover.
   * Can resolve data synchronously or asynchronously. Optional if schema is provided.
   */
  resolveData?: PopoverResolver<TData, TContext>;

  /** Optional initial context values passed to the data resolver. */
  initialContext?: TContext;

  /** Click outside configuration settings (enabled by default). */
  clickOutside?: ClickOutsideConfig;

  /** If true (default), enables closing topmost active popovers on Escape keydown. */
  enableKeyboardClose?: boolean;

  /**
   * If true, closing a parent popover will also recursively close all of its pinned descendants.
   * Defaults to false (pinned descendants remain open).
   */
  closePinnedDescendants?: boolean;

  /** Optional custom synchronous or asynchronous cache provider. */
  cache?: PopoverCache<TData>;

  /** Global default settings for boundary collision checking. */
  collision?: CollisionConfig;

  /** If true, enables keyboard arrow key navigation (default: true). */
  enableArrowNavigation?: boolean;

  /** True to allow dragging when popover card is pinned/floating (default: true). */
  allowDragWhenPinned?: boolean;

  /** True to allow dragging when popover card is unpinned/trailing (default: true). */
  allowDragWhenUnpinned?: boolean;

  /** If true, prints Zustand state updates to the console (default: false). */
  debug?: boolean;

  /** Horizontal offset step applied per level of the cascade trail (default: 8px). */
  cascadeOffsetStep?: number;

  /** Duration of the exit transition in milliseconds before the card is unmounted (default: 0). */
  exitTransitionDuration?: number;

  /** Default distance gap offset override from trigger in pixels (default: 8px). */
  defaultOffset?: number;

  /** Base z-index offset applied to all popover layers (default: 1000). */
  baseZIndex?: number;

  /** Global default CSS animation class applied during mounting (default: 'mounting'). */
  mountingClassName?: string;

  /** Global default CSS animation class applied during unmounting (default: 'unmounting'). */
  unmountingClassName?: string;

  /** Global default CSS animation class applied during mounted (default: 'mounted'). */
  mountedClassName?: string;

  /** Responsive layout transformation mode ('auto' | 'popover' | 'bottom-sheet' | 'modal'). */
  responsiveMode?: 'auto' | 'popover' | 'bottom-sheet' | 'modal';

  /** Mobile viewport width breakpoint in pixels (default: 640). */
  mobileBreakpoint?: number;

  /** Active stack group zone ID filter (e.g. 'sidebar', 'canvas', or null for all). */
  stackGroup?: string | null;

  /** Global default focus lock options. */
  focusLockOptions?: FocusLockOptions;

  /** Global component slots overrides. */
  components?: PopoverSlotComponents;

  /** Base z-index depth offsets per stack group ID. */
  zIndexBaseMap?: ZIndexBaseMap;
}

/**
 * PopoverProvider component that instantiates the Zustand store and injects it
 * into the React context tree.
 *
 * @remarks
 * Instantiates the store once using `useState` and manages global event listeners for
 * Escape key closings (consolidated to avoid event duplication) and click-outside closures.
 *
 * @template TData - The type of resolved data payloads.
 * @template TContext - The type of global shared context.
 *
 * @param props - Provider configuration properties.
 * @returns The provider element wrapping children.
 *
 * @example
 * ```tsx
 * import { PopoverProvider, PopoverTrail } from 'popover-trail';
 * import { appSchema } from './schema';
 *
 * export function App() {
 *   return (
 *     <PopoverProvider schema={appSchema} clickOutside={{ enabled: true }}>
 *       <MainView />
 *       <PopoverTrail />
 *     </PopoverProvider>
 *   );
 * }
 * ```
 */
export function PopoverProvider<TData = unknown, TContext = unknown>({
  children,
  schema,
  resolveData,
  initialContext,
  clickOutside,
  enableKeyboardClose = true,
  closePinnedDescendants = false,
  cache,
  collision,
  enableArrowNavigation = true,
  debug = false,
  cascadeOffsetStep = 8,
  exitTransitionDuration = 0,
  defaultOffset = 8,
  baseZIndex = 1000,
  mountingClassName = 'mounting',
  unmountingClassName = 'unmounting',
  mountedClassName = 'mounted',
  responsiveMode = 'auto',
  stackGroup = null,
  components,
  zIndexBaseMap,
}: PopoverProviderProps<TData, TContext>) {
  validateProviderResolver(Boolean(resolveData || schema));
  validateCascadeStep(cascadeOffsetStep);
  validateDefaultOffset(defaultOffset);
  validateBaseZIndex(baseZIndex);
  validateExitDuration(exitTransitionDuration);

  const activeResolver = useMemo<PopoverResolver<TData, TContext>>(() => {
    if (resolveData) return resolveData;
    const schemaInstance = schema as
      | { createResolver?: <TC = TContext>() => PopoverResolver<TData, TC> }
      | undefined;
    if (schemaInstance && typeof schemaInstance.createResolver === 'function') {
      return schemaInstance.createResolver();
    }
    return () =>
      Promise.reject(new Error('No resolveData callback or schema provided to PopoverProvider'));
  }, [resolveData, schema]);

  // Use useState to instantiate the store once
  const [store] = useState(() =>
    createPopoverStore<TData, TContext>(activeResolver, initialContext, cache),
  );

  // Synchronize all provider props to the store in a single effect to avoid
  // 10 separate render cycles when multiple props change simultaneously
  useEffect(() => {
    store.getState().batchUpdates(() => {
      const state = store.getState();
      state.setEnableArrowNavigation(Boolean(enableArrowNavigation));
      state.setDebug(Boolean(debug));
      state.setCascadeOffsetStep(Number(cascadeOffsetStep));
      state.setExitTransitionDuration(Number(exitTransitionDuration));
      state.setDefaultOffset(Number(defaultOffset));
      state.setBaseZIndex(Number(baseZIndex));
      state.setGlobalAnimationClassNames(
        String(mountingClassName),
        String(unmountingClassName),
        String(mountedClassName),
      );
      state.setContext(initialContext as TContext);
      state.setResolveData(activeResolver);
      state.setClosePinnedDescendants(Boolean(closePinnedDescendants));
      state.setResponsiveMode(responsiveMode);
      state.setStackGroupFilter(stackGroup);

      if (!isDeepEqual(state.collisionConfig, collision ?? null)) {
        state.setCollisionConfig(collision ?? null);
      }
      if (state.components !== (components ?? null)) {
        state.setSlotComponents(components ?? null);
      }
      if (!isDeepEqual(state.zIndexBaseMap, zIndexBaseMap ?? null)) {
        state.setZIndexBaseMap(zIndexBaseMap ?? null);
      }
    });
  }, [
    store,
    enableArrowNavigation,
    debug,
    cascadeOffsetStep,
    exitTransitionDuration,
    defaultOffset,
    baseZIndex,
    mountingClassName,
    unmountingClassName,
    mountedClassName,
    initialContext,
    activeResolver,
    closePinnedDescendants,
    collision,
    responsiveMode,
    stackGroup,
    components,
    zIndexBaseMap,
  ]);

  // Cleanup on Provider unmount: abort all in-flight requests and reset state
  useEffect(() => {
    return () => {
      store.getState().destroy();
    };
  }, [store]);

  // Handle Escape key closing globally (WAI-ARIA Accessibility compliance & single listener consolidation)
  const handleKeyDown = useCallback(
    (e: KeyboardEvent) => {
      if (!enableKeyboardClose) return;
      if (e.key === 'Escape') {
        const state = store.getState();
        const hasActive = state.trail.length > 0 || state.floating.length > 0;
        if (hasActive) {
          state.closeTopmost();
        }
      }
    },
    [enableKeyboardClose, store],
  );

  useEventListener('keydown', handleKeyDown);

  // Setup click outside logic if enabled
  const enabled = clickOutside?.enabled;
  const ignoreClass = clickOutside?.ignoreClass;
  const popoverSelector = clickOutside?.popoverSelector ?? '.popover-card';

  useEffect(() => {
    if (!enabled) return;

    const escapedIgnoreClass = ignoreClass
      ? typeof CSS !== 'undefined' && typeof CSS.escape === 'function'
        ? `.${CSS.escape(ignoreClass)}`
        : `.${ignoreClass.replace(/[^a-zA-Z0-9_-]/g, '')}`
      : null;

    const handleClickOutside = (e: MouseEvent) => {
      const path = getEventPath(e);
      const target = getEventTarget<HTMLElement>(e) ?? (e.target as HTMLElement);
      const state = store.getState();

      if (state.trail.length === 0) return;

      // Use composedPath to handle detached DOM nodes and Shadow DOM correctly
      const clickedInside = path.some((el) => {
        if (el instanceof HTMLElement) {
          try {
            if (el.matches(popoverSelector)) return true;
            if (escapedIgnoreClass && el.matches(escapedIgnoreClass)) return true;
          } catch {
            if (ignoreClass && el.classList.contains(ignoreClass)) return true;
          }
        }
        return false;
      });

      if (clickedInside) return;

      // If click target is the anchor element itself or contained within path, ignore
      if (
        state.anchorElement &&
        (path.includes(state.anchorElement) || state.anchorElement.contains(target))
      ) {
        return;
      }

      // Click is outside, clear the active trail!
      state.clearTrail();
    };

    document.addEventListener('mousedown', handleClickOutside);
    return () => document.removeEventListener('mousedown', handleClickOutside);
  }, [enabled, ignoreClass, popoverSelector, store]);

  return (
    <PopoverStoreContext.Provider value={store as unknown as StoreApi<PopoverStore>}>
      {children}
    </PopoverStoreContext.Provider>
  );
}

/**
 * Custom selector hook for direct access to reactive slices of the Popover Zustand store.
 *
 * @template TData - The type of resolved data payloads.
 * @template TContext - The type of global shared context.
 * @template TSelected - The selected slice type.
 *
 * @param selector - Selector function extracting values from state.
 * @returns The reactive value slice.
 * @throws {Error} If called outside a PopoverProvider.
 */


/**
 * Custom selector hook for direct access to reactive slices of the Popover Zustand store.
 *
 * @template TSelected - The extracted state slice type.
 * @template TData - The type of resolved data payloads.
 * @template TContext - The type of global shared context.
 *
 * @param selector - Function to extract a slice of the store state.
 * @param equalityFn - Optional custom equality function to prevent redundant re-renders.
 * @returns The selected state slice.
 * @throws {Error} If called outside a `<PopoverProvider>`.
 *
 * @example
 * ```tsx
 * const activeCount = usePopoverStore((state) => state.trail.length);
 * ```
 *
 * @see {@link PopoverProvider}
 * @see {@link usePopoverStoreApi}
 */
export function usePopoverStore<TSelected, TData = unknown, TContext = unknown>(
  selector: (state: PopoverStore<TData, TContext>) => TSelected,
  equalityFn?: (a: TSelected, b: TSelected) => boolean,
): TSelected {
  const store = usePopoverStoreApi<TData, TContext>();
  const slice = useStore(store, selector as (state: PopoverStore<TData, TContext>) => TSelected);
  const prevRef = useRef<TSelected>(slice);

  if (equalityFn && prevRef.current !== slice && !equalityFn(prevRef.current, slice)) {
    prevRef.current = slice;
  }

  return equalityFn ? prevRef.current : slice;
}

/**
 * Hook to retrieve the raw store API instance directly, without subscribing to state changes.
 * Useful for performance-sensitive imperative writes (e.g. inside drag events or event handlers).
 *
 * @template TData - The type of resolved data payloads.
 * @template TContext - The type of global shared context.
 *
 * @returns The raw Zustand StoreApi instance matching PopoverStore.
 * @throws {Error} If called outside a `<PopoverProvider>`.
 *
 * @example
 * ```tsx
 * const storeApi = usePopoverStoreApi();
 * const currentState = storeApi.getState();
 * ```
 *
 * @see {@link PopoverProvider}
 * @see {@link usePopoverStore}
 */
export function usePopoverStoreApi<TData = unknown, TContext = unknown>(): StoreApi<
  PopoverStore<TData, TContext>
> {
  const store = useContext(PopoverStoreContext);
  invariant(store, 'usePopoverStoreApi must be used within a PopoverProvider');
  return store as StoreApi<PopoverStore<TData, TContext>>;
}

/**
 * Hook to retrieve public popover store action dispatch methods.
 *
 * @remarks
 * Excludes internal state lifecycle actions like `openRoot` and `destroy`.
 *
 * @template TData - The type of resolved data payloads.
 * @template TContext - The type of global shared context.
 * @returns Object containing dispatch actions.
 */
export function usePopoverActions<
  TData = unknown,
  TContext = unknown,
  TPopoverKey extends string = string,
>(): Readonly<PopoverStore<TData, TContext, TPopoverKey>['actions']> {
  const store = useContext(PopoverStoreContext);
  if (!store) {
    throw new Error('usePopoverActions must be used within a PopoverProvider');
  }
  return store.getState().actions as Readonly<
    PopoverStore<TData, TContext, TPopoverKey>['actions']
  >;
}

import {
  usePopoverTrail,
  usePopoverFloating,
  usePopoverOffsets,
  useIsPopoverPinned,
  usePopoverEntry,
  usePopoverZIndex,
  useIsPopoverTopMost,
  usePopoverOffset,
  usePopoverContext,
  usePopoverCollisionConfig,
  useIsPopoverOpen,
  usePopover,
  usePopoverData,
  usePopoverHydration,
  type PopoverHydrationState,
} from './hooks/usePopoverSelectors';

export {
  usePopoverTrail,
  usePopoverFloating,
  usePopoverOffsets,
  useIsPopoverPinned,
  usePopoverEntry,
  usePopoverZIndex,
  useIsPopoverTopMost,
  usePopoverOffset,
  usePopoverContext,
  usePopoverCollisionConfig,
  useIsPopoverOpen,
  usePopover,
  usePopoverData,
  usePopoverHydration,
  type PopoverHydrationState,
};

export {
  usePopoverTimeline,
  type PopoverTimelineItem,
  type UsePopoverTimelineResult,
} from './hooks/usePopoverTimeline';

export { usePopoverTrigger, usePopoverNestedTrigger } from './hooks/usePopoverTriggers';
export { PopoverPortal, type PopoverPortalProps } from './components/PopoverPortal';



/**
 * Factory creating pre-bound PopoverProvider and custom hooks for a specific shared global app TContext.
 * Eliminates repeating generic parameter types across components.
 *
 * @template TContext - Global shared context type.
 *
 * @example
 * ```tsx
 * const { Provider, useContext, useActions } = definePopoverContext<MyGlobalContext>();
 * ```
 *
 * @see {@link PopoverProvider}
 * @see {@link usePopoverContext}
 */
export function definePopoverContext<TContext = unknown>() {
  return {
    useContext: () => usePopoverContext<TContext>(),
    useActions: <TData = unknown>() => usePopoverActions<TData, TContext>(),
    useStoreApi: <TData = unknown>() => usePopoverStoreApi<TData, TContext>(),
    Provider: PopoverProvider as React.ComponentType<PopoverProviderProps<unknown, TContext>>,
  };
}
