import { describe, it, expect } from 'vitest';
import * as PopoverLib from './index';

describe('index entry point exports', () => {
  it('re-exports all core components, functions, and utilities', () => {
    expect(PopoverLib.PopoverProvider).toBeDefined();
    expect(PopoverLib.PopoverCard).toBeDefined();
    expect(PopoverLib.PopoverTrigger).toBeDefined();
    expect(PopoverLib.PopoverTrail).toBeDefined();
    expect(PopoverLib.PopoverPortal).toBeDefined();
    expect(PopoverLib.createPopoverStore).toBeDefined();
    expect(PopoverLib.createPopoverSchema).toBeDefined();
    expect(PopoverLib.createPopoverTrail).toBeDefined();
    expect(PopoverLib.PopoverError).toBeDefined();
    expect(PopoverLib.Ok).toBeDefined();
    expect(PopoverLib.Err).toBeDefined();
    expect(PopoverLib.mapErr).toBeDefined();
    expect(PopoverLib.unwrap).toBeDefined();
    expect(PopoverLib.matchResult).toBeDefined();
    expect(PopoverLib.CompositeDisposable).toBeDefined();
    expect(PopoverLib.applyThemeTokens).toBeDefined();
    expect(PopoverLib.removeThemeTokens).toBeDefined();
    expect(PopoverLib.PopoverMiddlewareEngine).toBeDefined();
    expect(PopoverLib.isPromise).toBeDefined();
    expect(PopoverLib.shallowEqual).toBeDefined();
    expect(PopoverLib.isDeepEqual).toBeDefined();
    expect(PopoverLib.clsx).toBeDefined();
    expect(PopoverLib.isPushNestedEvent).toBeDefined();
    expect(PopoverLib.isResolveStartEvent).toBeDefined();
    expect(PopoverLib.isResolveSuccessEvent).toBeDefined();
    expect(PopoverLib.isResolveErrorEvent).toBeDefined();
    expect(PopoverLib.definePopoverConfig).toBeDefined();
    expect(PopoverLib.definePopoverMiddleware).toBeDefined();
    expect(PopoverLib.updateEntryInLists).toBeDefined();
    expect(PopoverLib.getSnapshotStatePatch).toBeDefined();
    expect(PopoverLib.matchEntryState).toBeDefined();
    expect(PopoverLib.defineStoreSlice).toBeDefined();
    expect(PopoverLib.createPopoverEvent).toBeDefined();
  });
});
