/**
 * Single Source of Truth (SSOT) Warning Codes Registry.
 * Clean Architecture Layer 1: Core Kernel (Pure Functional Domain).
 *
 * @module validators/warningCodes
 */

export const PopoverWarningCode = {
  INVALID_POPOVER_KEY: 'PT-101',
  INVALID_PLACEMENT: 'PT-102',
  INVALID_HOVER_OPEN_DELAY: 'PT-103',
  INVALID_HOVER_CLOSE_DELAY: 'PT-104',
  CIRCULAR_CASCADE_LOOP: 'PT-105',
  CARD_SUBCOMPONENT_OUTSIDE_SCOPE: 'PT-106',
  TIMELINE_SUBCOMPONENT_OUTSIDE_SCOPE: 'PT-107',
  UNDEFINED_SCHEMA_KEY: 'PT-108',
  INVALID_CASCADE_OFFSET_STEP: 'PT-109',
  INVALID_DEFAULT_OFFSET: 'PT-110',
  INVALID_BASE_Z_INDEX: 'PT-111',
  INVALID_EXIT_TRANSITION_DURATION: 'PT-112',
  MISSING_RESOLVER_OR_SCHEMA: 'PT-113',
  INVALID_DRAG_OFFSET: 'PT-114',
  CASCADE_DEPTH_EXCEEDED: 'PT-115',
  INVALID_STACK_GROUP: 'PT-116',
  INVALID_HISTORY_CAPACITY: 'PT-117',
  MISSING_TRIGGER_EVENT: 'PT-118',
  SHARED_MEMORY_UNSUPPORTED: 'PT-119',
  HYDRATION_ERROR: 'PT-120',
  INVALID_PIN_DRAG_STATE: 'PT-121',
  INVALID_STORAGE_KEY: 'PT-122',
  INVALID_QUADTREE_BOUNDS: 'PT-123',
  INVALID_FSM_TRANSITION: 'PT-124',
  MISSING_PORTAL_CONTAINER: 'PT-125',
  INVALID_FACTORY_PLACEMENT: 'PT-126',
  INVALID_STORE_INSTANCE: 'PT-127',
  SCHEMA_CIRCULAR_CHILD: 'PT-128',
  RESOLVER_TIMEOUT: 'PT-129',
  PORTAL_EXCLUSION: 'PT-130',
} as const;

export type PopoverWarningCode =
  | (typeof PopoverWarningCode)[keyof typeof PopoverWarningCode]
  | (string & {});
